plugins {
    id 'eclipse'
    id 'idea'
    id 'maven-publish'
    id 'net.neoforged.moddev' version '2.0.42-beta'
}

version = "${minecraft_version}-${mod_version}"
group = mod_group_id

base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neoforge_version

    runs {
        client {
            client()
        }

        server {
            server()
            programArgument '--nogui'
        }

        data {
            data()
            programArguments.addAll '--mod', mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

sourceSets.main.resources { srcDir 'src/generated/resources' }

repositories {
    maven { name = "Progwml6"; url = "https://dvs1.progwml6.com/files/maven/" }
    maven { name = "BlameJared"; url = "https://maven.blamejared.com" }
    maven { name = "Thehippomaster"; url = "https://maven.theillusivec4.top/" }
    maven { name = "GeckoLib"; url = "https://dl.cloudsmith.io/public/geckolib3/geckolib/maven/" }
    maven { name = "KosmX"; url = "https://maven.kosmx.dev/" }
    maven { name = "BreakInBlocks"; url = "https://maven.breakinblocks.com/releases" }
    maven {
        name = "CurseForge"
        url = "https://cursemaven.com"
        content { includeGroup "curse.maven" }
    }
    maven {
        name = "Modrinth"
        url = "https://api.modrinth.com/maven"
        content { includeGroup "maven.modrinth" }
    }
}

dependencies {
    implementation "com.breakinblocks.neovitae:neovitae:${neovitae_version}"

    compileOnly "curse.maven:modonomicon-538392:7771524"
    runtimeOnly "curse.maven:modonomicon-538392:7771524"

    compileOnly "curse.maven:jei-238222:${jei_cursemaven_id}"
    runtimeOnly "curse.maven:jei-238222:${jei_cursemaven_id}"

    compileOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}:api"
    runtimeOnly "top.theillusivec4.curios:curios-neoforge:${curios_version}"

    compileOnly "curse.maven:geckolib-388172:${geckolib_cursemaven_id}"
    runtimeOnly "curse.maven:geckolib-388172:${geckolib_cursemaven_id}"

    compileOnly files('libs/player-animation-lib-2.0.1+1.21.1.jar')
    runtimeOnly files('libs/player-animation-lib-2.0.1+1.21.1.jar')

    compileOnly "curse.maven:lodestone-616457:${lodestone_cursemaven_id}"
    runtimeOnly "curse.maven:lodestone-616457:${lodestone_cursemaven_id}"

    compileOnly files('libs/modopedia-1.1.5-neoforge.jar')
    runtimeOnly files('libs/modopedia-1.1.5-neoforge.jar')

    compileOnly "curse.maven:ars-nouveau-401955:${arsnouveau_cursemaven_id}"
    runtimeOnly "curse.maven:ars-nouveau-401955:${arsnouveau_cursemaven_id}"

    compileOnly "curse.maven:irons-spells-n-spellbooks-855414:${ironsspells_cursemaven_id}"
    runtimeOnly "curse.maven:irons-spells-n-spellbooks-855414:${ironsspells_cursemaven_id}"

    compileOnly "curse.maven:malum-484064:${malum_cursemaven_id}"
    runtimeOnly "curse.maven:malum-484064:${malum_cursemaven_id}"

    runtimeOnly "curse.maven:jade-324717:${jade_cursemaven_id}"
}

tasks.named('processResources', ProcessResources).configure {
    var replaceProperties = [
            minecraft_version: minecraft_version,
            minecraft_version_range: minecraft_version_range,
            neoforge_version: neoforge_version,
            neoforge_version_range: neoforge_version_range,
            loader_version_range: loader_version_range,
            mod_id: mod_id,
            mod_name: mod_name,
            mod_license: mod_license,
            mod_version: mod_version,
            mod_authors: mod_authors,
            mod_description: mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

tasks.named('jar', Jar).configure {
    manifest {
        attributes([
                'Specification-Title'     : mod_id,
                'Specification-Vendor'    : mod_authors,
                'Specification-Version'   : '1',
                'Implementation-Title'    : project.name,
                'Implementation-Version'  : project.jar.archiveVersion,
                'Implementation-Vendor'   : mod_authors,
                'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}

publishing {
    publications {
        register('mavenJava', MavenPublication) {
            artifact jar
        }
    }
    repositories {
        maven {
            name = "BreakInBlocks"
            url = version.toString().endsWith("-SNAPSHOT") ?
                "https://maven.breakinblocks.com/snapshots" :
                "https://maven.breakinblocks.com/releases"
            credentials {
                username = System.getenv("MAVEN_USER") ?: ""
                password = System.getenv("MAVEN_TOKEN") ?: ""
            }
        }
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}
