package com.breakinblocks.animusnv.datagen;

import com.klikli_dev.modonomicon.api.datagen.LanguageProviderCache;
import com.klikli_dev.modonomicon.api.datagen.ModonomiconLanguageProvider;
import com.breakinblocks.animusnv.Constants;
import net.minecraft.data.PackOutput;
import net.neoforged.neoforge.common.data.LanguageProvider;

public class AnimusLanguageProvider extends LanguageProvider implements ModonomiconLanguageProvider {
    private final LanguageProviderCache langCache;

    public AnimusLanguageProvider(PackOutput output, LanguageProviderCache langCache) {
        super(output, Constants.Mod.MODID, "en_us");
        this.langCache = langCache;
    }

    @Override
    public void accept(String key, String value) {
        this.add(key, value);
    }

    @Override
    protected void addTranslations() {
        // Book translations are added by the book provider via the ModonomiconLanguageProvider interface.
        add("advancement.animusnv.arcane_blood.description", "Merge magic and blood by creating a Blood-Infused Spellbook");
        add("advancement.animusnv.arcane_blood.title", "Arcane Blood");
        add("advancement.animusnv.blood_born_flora.description", "Obtain a Blood Sapling to grow your own Blood Wood trees");
        add("advancement.animusnv.blood_born_flora.title", "Blood-Born Flora");
        add("advancement.animusnv.crystallized_power.description", "Create a Crystallized Spiritus Block, required for the Transcendent Ara Vitae");
        add("advancement.animusnv.crystallized_power.title", "Crystallized Power");
        add("advancement.animusnv.death_incarnate.description", "Wield the Hand of Death, a soul-reaping weapon with lifesteal and execute");
        add("advancement.animusnv.death_incarnate.title", "Death Incarnate");
        add("advancement.animusnv.equivalence.description", "Craft the Sigil of Equivalency to effortlessly transmute blocks");
        add("advancement.animusnv.equivalence.title", "Equivalence");
        add("advancement.animusnv.fragment_of_life.description", "Acquire a Fragment of Healing, a permanent passive health buff");
        add("advancement.animusnv.fragment_of_life.title", "Fragment of Life");
        add("advancement.animusnv.heavenly_wrath.description", "Forge the Sigil of Heavenly Wrath to smite your enemies from above");
        add("advancement.animusnv.heavenly_wrath.title", "Heavenly Wrath");
        add("advancement.animusnv.living_weapon.description", "Craft a weapon empowered by Spiritus - Sentient Spear, Shield, or Runic Scythe");
        add("advancement.animusnv.living_weapon.title", "Living Weapon");
        add("advancement.animusnv.root.description", "Craft a Sanguine Diviner to begin your journey into the deeper arts of Vitaemancy");
        add("advancement.animusnv.root.title", "Animus Awakens");
        add("advancement.animusnv.sanguine_scroll.description", "Craft a Sanguine Scroll to cast spells powered by Essentia Vitae");
        add("advancement.animusnv.sanguine_scroll.title", "Sanguine Scroll");
        add("advancement.animusnv.temporal_mastery.description", "Create the Sigil of Temporal Dominance to bend time to your will");
        add("advancement.animusnv.temporal_mastery.title", "Temporal Mastery");
        add("advancement.animusnv.tier6_ascension.description", "Build a Tier 6 Ara Vitae using Crystallized Spiritus Blocks");
        add("advancement.animusnv.tier6_ascension.title", "Tier 6 Ascension");
        add("advancement.animusnv.transcendence.description", "Craft the Transcendent Orb of Vitae, the highest-capacity Orb of Vitae in the mod");
        add("advancement.animusnv.transcendence.title", "Transcendence");
        add("advancement.animusnv.willful_ascension.description", "Craft Willful Stone using Spiritus and compressed cobblestone");
        add("advancement.animusnv.willful_ascension.title", "Willful Ascension");
        add("animusnv.subtitle.awaken_core", "Blood Core awakens");
        add("animusnv.subtitle.execute", "Execution");
        add("animusnv.subtitle.fungal_slurp", "Fungi slurps Spiritus");
        add("animusnv.subtitle.ghostly", "Ghostly sound");
        add("animusnv.subtitle.naturesleach", "Nature's Leach drains");
        add("animusnv.subtitle.ninja_time", "Monk empowered");
        add("animusnv.subtitle.vengefulspiritambient", "Vindicta spirit whispers");
        add("animusnv.upgrade.arcane_channeling", "Arcane Channeling");
        add("animusnv.upgrade.arcane_channeling.level.1", "Mana Cost -5%");
        add("animusnv.upgrade.arcane_channeling.level.2", "Mana Cost -10%");
        add("animusnv.upgrade.arcane_channeling.level.3", "Cooldown -5%");
        add("animusnv.upgrade.arcane_channeling.level.4", "Spells Trigger Armor");
        add("animusnv.upgrade.arcane_channeling.level.5", "Casting Grants Resistance");
        add("animusnv.upgrade.source_attunement", "Source Attunement");
        add("animusnv.upgrade.source_attunement.level.1", "Spell Damage +5%");
        add("animusnv.upgrade.source_attunement.level.2", "Spell Damage +10%");
        add("animusnv.upgrade.source_attunement.level.3", "Spell Damage +15%");
        add("animusnv.upgrade.source_attunement.level.4", "Spell Damage +20% & Mana Regen");
        add("animusnv.upgrade.source_attunement.level.5", "Spell Damage +25% & Mana Cost -20%");
        add("attribute.animusnv.unarmed_damage", "Unarmed Damage");
        add("block.animusnv.antilife", "AntiLife");
        add("block.animusnv.arcane_rune", "Arcane Rune");
        add("block.animusnv.blood_core", "Blood Core");
        add("block.animusnv.blood_leaves", "Blood Leaves");
        add("block.animusnv.blood_sapling", "Blood Sapling");
        add("block.animusnv.blood_wood", "Blood Wood Log");
        add("block.animusnv.blood_wood_fence", "Blood Wood Fence");
        add("block.animusnv.blood_wood_fence_gate", "Blood Wood Fence Gate");
        add("block.animusnv.blood_wood_planks", "Blood Wood Planks");
        add("block.animusnv.blood_wood_slab", "Blood Wood Slab");
        add("block.animusnv.blood_wood_stairs", "Blood Wood Stairs");
        add("block.animusnv.blood_wood_stripped", "Stripped Blood Wood Log");
        add("block.animusnv.crystallized_spiritus_block", "Crystallized Spiritus Block");
        add("block.animusnv.sanguine_rectifier", "Sanguine Rectifier");
        add("block.animusnv.diabolical_fungi", "Diabolical Fungi");
        add("block.animusnv.imperfect_ritual_stone", "Imperfect Ritual Stone");
        add("block.animusnv.rune_unleashed_nature", "Rune of Unleashed Nature");
        add("block.animusnv.willful_stone", "Willful Stone");
        add("block.animusnv.willful_stone_black", "Black Willful Stone");
        add("block.animusnv.willful_stone_blue", "Blue Willful Stone");
        add("block.animusnv.willful_stone_brown", "Brown Willful Stone");
        add("block.animusnv.willful_stone_cyan", "Cyan Willful Stone");
        add("block.animusnv.willful_stone_green", "Green Willful Stone");
        add("block.animusnv.willful_stone_light_blue", "Light Blue Willful Stone");
        add("block.animusnv.willful_stone_light_gray", "Light Gray Willful Stone");
        add("block.animusnv.willful_stone_lime", "Lime Willful Stone");
        add("block.animusnv.willful_stone_magenta", "Magenta Willful Stone");
        add("block.animusnv.willful_stone_orange", "Orange Willful Stone");
        add("block.animusnv.willful_stone_pink", "Pink Willful Stone");
        add("block.animusnv.willful_stone_purple", "Purple Willful Stone");
        add("block.animusnv.willful_stone_red", "Red Willful Stone");
        add("block.animusnv.willful_stone_white", "White Willful Stone");
        add("block.animusnv.willful_stone_yellow", "Yellow Willful Stone");
        add("commands.animusnv.fillgem.not_gem", "You must be holding a Spiritus Gem");
        add("commands.animusnv.fillgem.success", "Filled Spiritus Gem to maximum capacity");
        add("commands.animusnv.fillwill.success", "Filled %s Spiritus in chunk to maximum");
        add("commands.animusnv.getev.success", "Current EV: %s");
        add("commands.animusnv.setev.success", "Set EV to %s");
        add("curios.identifier.bindingkey", "Binding Key Slot");
        add("curios.identifier.key", "Key Slot");
        add("fluid.animusnv.antilife", "AntiLife");
        add("fluid.animusnv.living_terra", "Living Terra");
        add("guide.animusnv.category.altar", "Ara Vitae");
        add("guide.animusnv.category.blocks", "Corruption & Fluids");
        add("guide.animusnv.category.bloodtrees", "Blood Trees");
        add("guide.animusnv.category.compatibility", "Modded Compatibility");
        add("guide.animusnv.category.intro", "Introduction");
        add("guide.animusnv.category.items", "Items & Tools");
        add("guide.animusnv.category.rituals", "Rituals");
        add("guide.animusnv.category.sigils", "Sigils");
        add("guide.animusnv.entry.activation_crystal_fragile", "Fragile Activation Crystal");
        add("guide.animusnv.entry.antilife", "AntiLife");
        add("guide.animusnv.entry.antilife_fluid", "AntiLife Fluid");
        add("guide.animusnv.entry.arcane_rune", "Arcane Rune");
        add("guide.animusnv.entry.blood_apple", "Blood Apple");
        add("guide.animusnv.entry.blood_infused_spellbook", "Blood-Infused Spellbook");
        add("guide.animusnv.entry.blood_orb_transcendent", "Transcendent Orb of Vitae");
        add("guide.animusnv.entry.blood_trees", "Blood Trees");
        add("guide.animusnv.entry.crystallized_spiritus", "Crystallized Spiritus");
        add("guide.animusnv.entry.crystallized_spiritus_block", "Crystallized Spiritus");
        add("guide.animusnv.entry.decorative_blocks", "Decorative Blocks");
        add("guide.animusnv.entry.diabolical_fungi", "Diabolical Fungi");
        add("guide.animusnv.entry.fragment_healing", "Fragment of Healing");
        add("guide.animusnv.entry.hand_of_death", "Hand of Death");
        add("guide.animusnv.entry.imperfect_ritual_boundless_skies", "Imperfect Ritual of Boundless Skies");
        add("guide.animusnv.entry.imperfect_ritual_clear_skies", "Imperfect Ritual of Clear Skies");
        add("guide.animusnv.entry.imperfect_ritual_enhancement", "Imperfect Ritual of Enhancement");
        add("guide.animusnv.entry.imperfect_ritual_hunger", "Imperfect Ritual of Hunger");
        add("guide.animusnv.entry.imperfect_ritual_iron_heart", "Imperfect Ritual of the Iron Heart");
        add("guide.animusnv.entry.imperfect_ritual_magi", "Imperfect Ritual of the Magi");
        add("guide.animusnv.entry.imperfect_ritual_manasteel_soul", "Imperfect Ritual of the Manasteel Soul");
        add("guide.animusnv.entry.imperfect_ritual_neptune_blessing", "Imperfect Ritual of Neptune's Blessing");
        add("guide.animusnv.entry.imperfect_ritual_reduction", "Imperfect Ritual of Reduction");
        add("guide.animusnv.entry.imperfect_ritual_regression", "Imperfect Ritual of Regression");
        add("guide.animusnv.entry.imperfect_ritual_soul_stained_blood", "Imperfect Ritual of Soul Stained Blood");
        add("guide.animusnv.entry.imperfect_ritual_stone", "Imperfect Ritual Stone");
        add("guide.animusnv.entry.imperfect_ritual_warden", "Imperfect Ritual of the Warden");
        add("guide.animusnv.entry.key_binding", "Key of Binding");
        add("guide.animusnv.entry.living_armor_ars_nouveau", "Sentient Armor & Ars Nouveau");
        add("guide.animusnv.entry.living_armor_spells", "Sentient Armor Spellcasting");
        add("guide.animusnv.entry.living_terra", "Living Terra");
        add("guide.animusnv.entry.mob_soul", "Mob Soul");
        add("guide.animusnv.entry.reagent_boundless_nature", "Reagent: Boundless Nature");
        add("guide.animusnv.entry.reagent_builder", "Reagent: Builder");
        add("guide.animusnv.entry.reagent_chains", "Reagent: Chains");
        add("guide.animusnv.entry.reagent_consumption", "Reagent: Consumption");
        add("guide.animusnv.entry.reagent_equivalency", "Reagent: Equivalency");
        add("guide.animusnv.entry.reagent_free_soul", "Reagent: Free Soul");
        add("guide.animusnv.entry.reagent_heavenly_wrath", "Reagent: Heavenly Wrath");
        add("guide.animusnv.entry.reagent_leach", "Reagent: Leach");
        add("guide.animusnv.entry.reagent_remedium", "Reagent: Remedium");
        add("guide.animusnv.entry.reagent_reparare", "Reagent: Reparare");
        add("guide.animusnv.entry.reagent_storm", "Reagent: Storm");
        add("guide.animusnv.entry.reagent_temporal_dominance", "Reagent: Temporal Dominance");
        add("guide.animusnv.entry.reagent_transposition", "Reagent: Transposition");
        add("guide.animusnv.entry.ritual_arcane_mastery", "Ritual of Arcane Mastery");
        add("guide.animusnv.entry.ritual_culling", "Ritual of Culling");
        add("guide.animusnv.entry.ritual_entropy", "Ritual of Entropy");
        add("guide.animusnv.entry.ritual_floral_supremacy", "Ritual of Floral Supremacy");
        add("guide.animusnv.entry.ritual_luna", "Ritual of Luna");
        add("guide.animusnv.entry.ritual_natures_leach", "Ritual of Nature's Leach");
        add("guide.animusnv.entry.ritual_nolite_ignem", "Ritual of Nolite Ignem");
        add("guide.animusnv.entry.ritual_animal_luring", "Ritual of Animal Luring");
        add("guide.animusnv.entry.ritual_persistence", "Ritual of Persistence");
        add("guide.animusnv.entry.ritual_relentless_tides", "Ritual of Relentless Tides");
        add("guide.animusnv.entry.ritual_reparare", "Ritual of Reparare");
        add("guide.animusnv.entry.ritual_serenity", "Ritual of Serenity");
        add("guide.animusnv.entry.ritual_siphon", "Ritual of Siphon");
        add("guide.animusnv.entry.ritual_sol", "Ritual of Sol");
        add("guide.animusnv.entry.ritual_source_vitaeum", "Ritual of Source Vitaeum");
        add("guide.animusnv.entry.ritual_steadfast_heart", "Ritual of Steadfast Heart");
        add("guide.animusnv.entry.ritual_unmaking", "Ritual of Unmaking");
        add("guide.animusnv.entry.rune_unleashed_nature", "Rune of Unleashed Nature");
        add("guide.animusnv.entry.runic_sentient_scythe", "Runic Sentient Scythe");
        add("guide.animusnv.entry.sanguine_diviner", "Sanguine Diviner");
        add("guide.animusnv.entry.sanguine_scrolls", "Sanguine Scrolls");
        add("guide.animusnv.entry.sentient_shield", "Sentient Shield");
        add("guide.animusnv.entry.sigil_boundless_nature", "Sigil of Boundless Nature");
        add("guide.animusnv.entry.sigil_builder", "Sigil of the Fast Builder");
        add("guide.animusnv.entry.sigil_chains", "Sigil of the Phantom Chain");
        add("guide.animusnv.entry.sigil_consumption", "Sigil of Consumption");
        add("guide.animusnv.entry.sigil_crimson_will", "Sigil of Crimson Will");
        add("guide.animusnv.entry.sigil_equivalency", "Sigil of Equivalency");
        add("guide.animusnv.entry.sigil_free_soul", "Sigil of the Free Soul");
        add("guide.animusnv.entry.sigil_heavenly_wrath", "Sigil of Heavenly Wrath");
        add("guide.animusnv.entry.sigil_leach", "Sigil of Nature's Leach");
        add("guide.animusnv.entry.sigil_monk", "Sigil of the Demon Monk");
        add("guide.animusnv.entry.sigil_remedium", "Sigil of Remedium");
        add("guide.animusnv.entry.sigil_reparare", "Sigil of Reparare");
        add("guide.animusnv.entry.sigil_storm", "Sigil of the Storm");
        add("guide.animusnv.entry.sigil_temporal_dominance", "Sigil of Temporal Dominance");
        add("guide.animusnv.entry.sigil_transposition", "Sigil of Transposition");
        add("guide.animusnv.entry.spears", "Spears");
        add("guide.animusnv.entry.tier6_altar", "Tier 6 Altar");
        add("guide.animusnv.entry.welcome", "Welcome to Animus");
        add("guide.animusnv.entry.willful_stone", "Willful Stone");
        add("guide.animusnv.landing_text", "A comprehensive guide detailing the Animus of the Sanguine Arts");
        add("guide.animusnv.name", "Codex Animus");
        add("item.animusnv.guide_book", "Codex Animus");
        add("item.animusnv.activation_crystal_fragile", "Fragile Activation Crystal");
        add("item.animusnv.antilife_bucket", "AntiLife Bucket");
        add("item.animusnv.blood_apple", "Blood Apple");
        add("item.animusnv.blood_infused_spellbook", "Blood-Infused Spellbook");
        add("item.animusnv.blood_orb_transcendent", "Transcendent Orb of Vitae");
        add("item.animusnv.fragment_healing", "Fragment of Healing");
        add("item.animusnv.hand_of_death", "Hand of Death");
        add("item.animusnv.hellforged_bow", "Hellforged Bow");
        add("item.animusnv.key_binding", "Key of Binding");
        add("item.animusnv.living_terra_bucket", "Living Terra Bucket");
        add("item.animusnv.mob_soul", "Mob Soul");
        add("item.animusnv.reagentboundlessnature", "Reagent: Boundless Nature");
        add("item.animusnv.reagentbuilder", "Reagent: Builder");
        add("item.animusnv.reagentchains", "Reagent: Chains");
        add("item.animusnv.reagentconsumption", "Reagent: Consumption");
        add("item.animusnv.reagentequivalency", "Reagent: Equivalency");
        add("item.animusnv.reagentfist", "Reagent: Fist");
        add("item.animusnv.reagentfreesoul", "Reagent: Free Soul");
        add("item.animusnv.reagentheavelywrath", "Reagent: Heavenly Wrath");
        add("item.animusnv.reagentleach", "Reagent: Leach");
        add("item.animusnv.reagentremendium", "Reagent: Remedium");
        add("item.animusnv.reagentreparare", "Reagent: Reparare");
        add("item.animusnv.reagentstorm", "Reagent: Storm");
        add("item.animusnv.reagenttemporaldominance", "Reagent: Temporal Dominance");
        add("item.animusnv.reagenttransposition", "Reagent: Transposition");
        add("item.animusnv.runic_sentient_scythe", "Runic Sentient Scythe");
        add("item.animusnv.sanguine_diviner", "Sanguine Diviner");
        add("item.animusnv.sanguine_scroll_rasa", "Sanguine Scroll (Rasa)");
        add("item.animusnv.sanguine_scroll_spiritus", "Sanguine Scroll (Spiritus)");
        add("item.animusnv.sanguine_scroll_aetherea", "Sanguine Scroll (Aetherea)");
        add("item.animusnv.sanguine_scroll_animata", "Sanguine Scroll (Animata)");
        add("item.animusnv.sanguine_scroll_robur", "Sanguine Scroll (Robur)");
        add("item.animusnv.sentient_bow", "Sentient Bow");
        add("item.animusnv.sentient_shield", "Sentient Shield");
        add("item.animusnv.sigil_boundless_nature", "Sigil of Boundless Nature");
        add("item.animusnv.sigil_builder", "Sigil of the Fast Builder");
        add("item.animusnv.sigil_chains", "Sigil of the Phantom Chain");
        add("item.animusnv.sigil_consumption", "Sigil of Consumption");
        add("item.animusnv.sigil_crimson_will", "Sigil of Crimson Will");
        add("item.animusnv.sigil_equivalency", "Sigil of Equivalency");
        add("item.animusnv.sigil_free_soul", "Sigil of the Free Soul");
        add("item.animusnv.sigil_heavenly_wrath", "Sigil of Heavenly Wrath");
        add("item.animusnv.sigil_leach", "Sigil of Nature's Leach");
        add("item.animusnv.sigil_monk", "Sigil of the Demon Monk");
        add("item.animusnv.sigil_remedium", "Sigil of Remedium");
        add("item.animusnv.sigil_reparare", "Sigil of Reparare");
        add("item.animusnv.sigil_storm", "Sigil of the Storm");
        add("item.animusnv.sigil_temporal_dominance", "Sigil of Temporal Dominance");
        add("item.animusnv.sigil_transposition", "Sigil of Transposition");
        add("item.animusnv.spear_bound", "Bound Spear");
        add("item.animusnv.spear_diamond", "Diamond Spear");
        add("item.animusnv.spear_iron", "Iron Spear");
        add("item.animusnv.spear_sentient", "Sentient Spear");
        add("itemGroup.animusnv", "Animus: NeoVitae");
        add("jei.animusnv.antilife.info", "Created when lightning strikes Essentia Vitae fluid from NeoVitae. Spreads to adjacent blocks, converting them into AntiLife. When touching Essentia Vitae, spreads as fluid instead.");
        add("jei.animusnv.antilife_block.info", "Created by the Sigil of Consumption or when AntiLife fluid touches solid blocks. Spreads to matching adjacent blocks up to the configured range.");
        add("jei.animusnv.blood_apple.info", "Blood Apples are obtained by harvesting Blood Tree Leaves. They restore 4 hunger and 9.6 saturation when eaten, and grant 200 EV to your Anima. Blood Trees grow from Blood Saplings, which can be created at the Ara Vitae.");
        add("jei.animusnv.blood_infused_spellbook.desc", "Right-click Ara Vitae while holding any Iron's Spellbook.");
        add("jei.animusnv.blood_infused_spellbook.title", "Create Blood-Infused Spellbook");
        add("jei.animusnv.blood_infused_spellbook.upgrade_desc", "Right-click Ara Vitae while holding the spellbook.");
        add("jei.animusnv.blood_infused_spellbook.upgrade_title", "Upgrade Blood-Infused Spellbook");
        add("jei.animusnv.category.altar_infusion", "Ara Vitae Infusion");
        add("jei.animusnv.category.imperfect_ritual", "Imperfect Rituals");
        add("jei.animusnv.crystallized_spiritus_block.info", "Crafted in the Tabula Vitae using endgame reagents. Required component for Tier 6 Ara Vitaes. Acts as a valid CRYSTAL component in altar structures.");
        add("jei.animusnv.imperfect_ritual.instruction", "Right-click Ritual Stone to activate");
        add("jei.animusnv.imperfect_ritual_stone.boundless_skies", "§6Ritual of Boundless Skies§r: Place Ancient Debris on top. Costs 10000 EV. Grants 15 minutes of creative flight.");
        add("jei.animusnv.imperfect_ritual_stone.enhancement", "§6Ritual of Enhancement§r: Place an Amethyst Block on top. Costs 5000 EV. Enhances all enchantments on mainhand item by 1 level. Cannot enhance already enhanced items.");
        add("jei.animusnv.imperfect_ritual_stone.hunger", "§6Ritual of Hunger§r: Place a Bone Block on top. Costs 500 EV. Makes you very hungry.");
        add("jei.animusnv.imperfect_ritual_stone.info", "Reusable ritual stone. Place a block on top and right-click to activate the ritual effect. Each use costs EV but the stone is not consumed.");
        add("jei.animusnv.imperfect_ritual_stone.iron_heart", "§6Ritual of the Iron Heart§r: Place an Arcane Anvil on top. Costs 3500 EV. Grants Echoing Strikes III for 15 minutes. Requires Iron's Spellbooks.");
        add("jei.animusnv.imperfect_ritual_stone.magi", "§6Ritual of the Magi§r: Place a Source Gem Block on top. Costs 2500 EV. Grants Mana Regen for 15 minutes. Requires Ars Nouveau.");
        add("jei.animusnv.imperfect_ritual_stone.manasteel_soul", "§6Ritual of the Manasteel Soul§r: Place a Manasteel Block on top. Costs 2500 EV. Grants Emptiness and Speed for 15 minutes. Requires Botania.");
        add("jei.animusnv.imperfect_ritual_stone.neptune_blessing", "§6Ritual of Neptune's Blessing§r: Place a Prismarine Block on top. Costs 2000 EV. Grants Water Breathing and Dolphin's Grace for 15 minutes.");
        add("jei.animusnv.imperfect_ritual_stone.reduction", "§6Ritual of Reduction§r: Place a Bookshelf on top. Costs 1000 EV. Removes enhanced mark and downgrades all enchantments by 1 level (minimum level 1).");
        add("jei.animusnv.imperfect_ritual_stone.regression", "§6Ritual of Regression§r: Place a Bookshelf on top. Costs 3000 EV. Removes repair cost from held item.");
        add("jei.animusnv.imperfect_ritual_stone.soul_stained_blood", "§6Ritual of the Soul Stained Blood§r: Place a Block of Hallowed Gold on top. Costs 2000 EV. Grants Gaia's Bulwark for 15 minutes. Requires Malum.");
        add("jei.animusnv.imperfect_ritual_stone.warden", "§6Ritual of the Warden§r: Place a Sculk Block on top. Costs 3000 EV. Grants Obsidian Cloak for 15 minutes.");
        add("jei.animusnv.living_terra.info", "Crafted in the Tabula Vitae using water, dirt, bone meal, and a sapling. When placed in the world, Living Terra slowly solidifies into dirt over time, useful for creating terrain or filling gaps.");
        add("jei.animusnv.ritual.boundless_skies.desc", "Grants 15 minutes of creative flight.");
        add("jei.animusnv.ritual.boundless_skies.name", "Ritual of Boundless Skies");
        add("jei.animusnv.ritual.clear_skies.desc", "Clears the weather, stopping rain and thunder.");
        add("jei.animusnv.ritual.clear_skies.name", "Ritual of Clear Skies");
        add("jei.animusnv.ritual.enhancement.desc", "Enhances all enchantments on mainhand item by 1 level.");
        add("jei.animusnv.ritual.enhancement.name", "Ritual of Enhancement");
        add("jei.animusnv.ritual.hunger.desc", "Makes you extremely hungry.");
        add("jei.animusnv.ritual.hunger.name", "Ritual of Hunger");
        add("jei.animusnv.ritual.iron_heart.desc", "Echoing Strikes III for 15 minutes.");
        add("jei.animusnv.ritual.iron_heart.name", "Ritual of the Iron Heart");
        add("jei.animusnv.ritual.magi.desc", "Mana Regen for 15 minutes.");
        add("jei.animusnv.ritual.magi.name", "Ritual of the Magi");
        add("jei.animusnv.ritual.manasteel_soul.desc", "Emptiness and Speed for 15 minutes.");
        add("jei.animusnv.ritual.manasteel_soul.name", "Ritual of the Manasteel Soul");
        add("jei.animusnv.ritual.neptune_blessing.desc", "Water Breathing and Dolphin's Grace for 15 minutes.");
        add("jei.animusnv.ritual.neptune_blessing.name", "Ritual of Neptune's Blessing");
        add("jei.animusnv.ritual.reduction.desc", "Removes enhanced mark, downgrades enchantments by 1 level.");
        add("jei.animusnv.ritual.reduction.name", "Ritual of Reduction");
        add("jei.animusnv.ritual.regression.desc", "Removes repair cost from held item (anvil penalty reset).");
        add("jei.animusnv.ritual.regression.name", "Ritual of Regression");
        add("jei.animusnv.ritual.soul_stained_blood.desc", "Gaia's Bulwark for 15 minutes.");
        add("jei.animusnv.ritual.soul_stained_blood.name", "Ritual of Soul Stained Blood");
        add("jei.animusnv.ritual.warden.desc", "Obsidian Cloak for 15 minutes.");
        add("jei.animusnv.ritual.warden.name", "Ritual of the Warden");
        add("jei.animusnv.sanguine_scroll.rasa", "§6Rasa Sanguine Scroll§r\nUses Tabula Rasa\n50 uses\n\n§cEV Cost:§r Base x Spell Level\nCommon: 2,000 | Uncommon: 4,000\nRare: 8,000 | Epic: 12,000\nLegendary: 16,000");
        add("jei.animusnv.sanguine_scroll.spiritus", "§6Spiritus Sanguine Scroll§r\nUses Tabula Spiritus\n400 uses\n\n§cEV Cost:§r Base x Spell Level\nCommon: 2,000 | Uncommon: 4,000\nRare: 8,000 | Epic: 12,000\nLegendary: 16,000");
        add("jei.animusnv.sanguine_scroll.desc", "Hold scroll + slate, right-click altar. EV based on spell.");
        add("jei.animusnv.sanguine_scroll.aetherea", "§6Aetherea Sanguine Scroll§r\nUses Tabula Aetherea\n600 uses\n\n§cEV Cost:§r Base x Spell Level\nCommon: 2,000 | Uncommon: 4,000\nRare: 8,000 | Epic: 12,000\nLegendary: 16,000\n\n§dMax EV (Level 5 Legendary): 80,000§r");
        add("jei.animusnv.sanguine_scroll.animata", "§6Animata Sanguine Scroll§r\nUses Tabula Animata\n200 uses\n\n§cEV Cost:§r Base x Spell Level\nCommon: 2,000 | Uncommon: 4,000\nRare: 8,000 | Epic: 12,000\nLegendary: 16,000");
        add("jei.animusnv.sanguine_scroll.info", "Sanguine Scrolls are reusable spell scrolls powered by Essentia Vitae instead of mana.\n\n§6Crafting:§r Right-click an Ara Vitae while holding an Iron's Spellbooks scroll in your main hand and a NeoVitae slate in your offhand. The altar consumes EV based on spell rarity and level.\n\n§6Usage:§r Right-click to cast the stored spell, consuming EV from your Anima. Each use damages the scroll's durability.");
        add("jei.animusnv.sanguine_scroll.robur", "§6Robur Sanguine Scroll§r\nUses Tabula Robur\n100 uses\n\n§cEV Cost:§r Base x Spell Level\nCommon: 2,000 | Uncommon: 4,000\nRare: 8,000 | Epic: 12,000\nLegendary: 16,000");
        add("jei.animusnv.sanguine_scroll.title.blank", "Sanguine Scroll (Rasa)");
        add("jei.animusnv.sanguine_scroll.title.demon", "Sanguine Scroll (Spiritus)");
        add("jei.animusnv.sanguine_scroll.title.ethereal", "Sanguine Scroll (Aetherea)");
        add("jei.animusnv.sanguine_scroll.title.imbued", "Sanguine Scroll (Animata)");
        add("jei.animusnv.sanguine_scroll.title.reinforced", "Sanguine Scroll (Robur)");
        add("living_upgrade.animusnv.arcane_channeling", "Arcane Channeling");
        add("living_upgrade.animusnv.source_attunement", "Source Attunement");
        add("ritual.animusnv.boundless_skies.success", "The boundless skies embrace you - creative flight granted!");
        add("ritual.animusnv.clear_skies.success", "The skies clear at your command!");
        add("ritual.animusnv.enhancement.already_enhanced", "This item has already been enhanced!");
        add("ritual.animusnv.enhancement.no_enchantments", "This item has no enchantments to enhance!");
        add("ritual.animusnv.enhancement.no_item", "You must be holding an item in your mainhand to perform this ritual!");
        add("ritual.animusnv.enhancement.success", "Item enchantments enhanced!");
        add("ritual.animusnv.hunger.success", "You feel extremely hungry...");
        add("ritual.animusnv.imperfect_stone.activated", "Ritual activated!");
        add("ritual.animusnv.imperfect_stone.no_ritual", "No ritual found for block: %s");
        add("ritual.animusnv.imperfect_stone.not_enough_ev", "Not enough EV! Need: %s");
        add("ritual.animusnv.imperfect_stone.ticket", "Imperfect Ritual: %s");
        add("ritual.animusnv.iron_heart.effect_not_found", "Could not find the Echoing Strikes effect from Iron's Spellbooks!");
        add("ritual.animusnv.iron_heart.requires_irons", "This ritual requires Iron's Spellbooks to be installed!");
        add("ritual.animusnv.iron_heart.success", "The power of echoing strikes flows through you...");
        add("ritual.animusnv.magi.effect_not_found", "Could not find the Mana Regen effect from Ars Nouveau!");
        add("ritual.animusnv.magi.requires_ars", "This ritual requires Ars Nouveau to be installed!");
        add("ritual.animusnv.magi.success", "Arcane energy surges through your veins...");
        add("ritual.animusnv.manasteel_soul.effect_not_found", "Could not find the Emptiness effect from Botania!");
        add("ritual.animusnv.manasteel_soul.requires_botania", "This ritual requires Botania to be installed!");
        add("ritual.animusnv.manasteel_soul.success", "Your soul merges with the essence of mana...");
        add("ritual.animusnv.neptune_blessing.success", "Neptune's blessing washes over you...");
        add("ritual.animusnv.reduction.no_enchantments", "This item has no enchantments to reduce!");
        add("ritual.animusnv.reduction.no_item", "You must be holding an item in your mainhand to perform this ritual!");
        add("ritual.animusnv.reduction.not_enhanced", "This item has no enhancements to reduce!");
        add("ritual.animusnv.reduction.success", "Item enhancements reduced!");
        add("ritual.animusnv.regression.no_cost", "This item has no repair cost to remove!");
        add("ritual.animusnv.regression.no_item", "You must be holding an item to perform this ritual!");
        add("ritual.animusnv.regression.success", "Repair cost removed!");
        add("ritual.animusnv.ritual_arcane_mastery", "Ritual of Arcane Mastery");
        add("ritual.animusnv.ritual_boundless_skies", "Ritual of Boundless Skies");
        add("ritual.animusnv.ritual_boundless_skies.desc", "Grants 15 minutes of flight");
        add("ritual.animusnv.ritual_clear_skies", "Ritual of Clear Skies");
        add("ritual.animusnv.ritual_clear_skies.desc", "Clears rain and thunder");
        add("ritual.animusnv.ritual_culling", "Ritual of Culling");
        add("ritual.animusnv.ritual_culling.effect.info", "Area to damage hostile mobs");
        add("ritual.animusnv.ritual_eldritch_will", "Ritual of Eldritch Will");
        add("ritual.animusnv.ritual_enhancement", "Ritual of Enhancement");
        add("ritual.animusnv.ritual_enhancement.desc", "Enhances all enchantments by 1 level");
        add("ritual.animusnv.ritual_entropy", "Ritual of Entropy");
        add("ritual.animusnv.ritual_floral_supremacy", "Ritual of Floral Supremacy");
        add("ritual.animusnv.ritual_hunger", "Ritual of Hunger");
        add("ritual.animusnv.ritual_hunger.desc", "Makes you extremely hungry");
        add("ritual.animusnv.ritual_iron_heart", "Ritual of the Iron Heart");
        add("ritual.animusnv.ritual_iron_heart.desc", "Echoing Strikes III for 15 minutes");
        add("ritual.animusnv.ritual_iron_heart.success", "Your strikes echo with power!");
        add("ritual.animusnv.ritual_luna", "Ritual of Luna");
        add("ritual.animusnv.ritual_magi", "Ritual of the Magi");
        add("ritual.animusnv.ritual_magi.desc", "Mana Regen III for 15 minutes");
        add("ritual.animusnv.ritual_magi.success", "Mana flows through you!");
        add("ritual.animusnv.ritual_manasteel_soul.desc", "Emptiness + Speed for 15 minutes");
        add("ritual.animusnv.ritual_natures_leach", "Ritual of Nature's Leach");
        add("ritual.animusnv.ritual_natures_leach.effect.info", "Area to drain life from plants");
        add("ritual.animusnv.ritual_neptune_blessing", "Ritual of Neptune's Blessing");
        add("ritual.animusnv.ritual_neptune_blessing.desc", "Water Breathing + Dolphin's Grace");
        add("ritual.animusnv.ritual_nolite_ignem", "Ritual of Nolite Ignem");
        add("ritual.animusnv.ritual_nolite_ignem.effect.info", "Area to extinguish fires");
        add("ritual.animusnv.ritual_animal_luring", "Ritual of Animal Luring");
        add("ritual.animusnv.ritual_animal_luring.spawn.info", "Area where peaceful mobs will spawn");
        add("ritual.animusnv.ritual_persistence", "Ritual of Persistence");
        add("ritual.animusnv.ritual_persistence.chunks.info", "Area of chunks to keep loaded");
        add("ritual.animusnv.ritual_reduction", "Ritual of Reduction");
        add("ritual.animusnv.ritual_reduction.desc", "Downgrades enchantments by 1 level");
        add("ritual.animusnv.ritual_regression", "Ritual of Regression");
        add("ritual.animusnv.ritual_regression.desc", "Removes repair cost from held item");
        add("ritual.animusnv.ritual_relentless_tides", "Ritual of Relentless Tides");
        add("ritual.animusnv.ritual_relentless_tides.effect.info", "Area to place fluids into");
        add("ritual.animusnv.ritual_relentless_tides.tank.info", "Location of fluid tank to drain from");
        add("ritual.animusnv.ritual_reparare", "Ritual of Reparare");
        add("ritual.animusnv.ritual_serenity", "Ritual of Serenity");
        add("ritual.animusnv.ritual_serenity.effect.info", "Area where hostile mob spawning is prevented");
        add("ritual.animusnv.ritual_siphon", "Ritual of Siphon");
        add("ritual.animusnv.ritual_siphon.effect.info", "Area to extract fluids from");
        add("ritual.animusnv.ritual_siphon.tank.info", "Location of fluid tank to fill");
        add("ritual.animusnv.ritual_sol", "Ritual of Sol");
        add("ritual.animusnv.ritual_soul_stained_blood", "Ritual of the Soul-Stained Blood");
        add("ritual.animusnv.ritual_soul_stained_blood.desc", "Sacrificial Empowerment III for 15 minutes");
        add("ritual.animusnv.ritual_soul_stained_blood.success", "The spirits empower your sacrifice!");
        add("ritual.animusnv.ritual_source_vitaeum", "Ritual of Source Vitaeum");
        add("ritual.animusnv.ritual_steadfast_heart", "Ritual of the Steadfast Heart");
        add("ritual.animusnv.ritual_unmaking", "Ritual of Unmaking");
        add("ritual.animusnv.ritual_warden", "Ritual of the Warden");
        add("ritual.animusnv.ritual_warden.desc", "Obsidian Cloak for 15 minutes");
        add("ritual.animusnv.soul_stained_blood.effect_not_found", "Could not find the Gaia's Bulwark effect from Malum!");
        add("ritual.animusnv.soul_stained_blood.no_effect", "The spirits cannot be reached...");
        add("ritual.animusnv.soul_stained_blood.requires_malum", "This ritual requires Malum to be installed!");
        add("ritual.animusnv.soul_stained_blood.success", "Gaia's protection flows through your blood...");
        add("ritual.animusnv.warden.success", "The Warden's protection envelops you...");
        add("ritual.neovitae.imperfect.ritual_boundless_skies", "Ritual of Boundless Skies");
        add("ritual.neovitae.imperfect.ritual_clear_skies", "Ritual of Clear Skies");
        add("ritual.neovitae.imperfect.ritual_enhancement", "Ritual of Enhancement");
        add("ritual.neovitae.imperfect.ritual_hunger", "Ritual of Hunger");
        add("ritual.neovitae.imperfect.ritual_iron_heart", "Ritual of the Iron Heart");
        add("ritual.neovitae.imperfect.ritual_magi", "Ritual of the Magi");
        add("ritual.neovitae.imperfect.ritual_manasteel_soul", "Ritual of the Manasteel Soul");
        add("ritual.neovitae.imperfect.ritual_neptune_blessing", "Ritual of Neptune's Blessing");
        add("ritual.neovitae.imperfect.ritual_reduction", "Ritual of Reduction");
        add("ritual.neovitae.imperfect.ritual_regression", "Ritual of Regression");
        add("ritual.neovitae.imperfect.ritual_soul_stained_blood", "Ritual of Soul-Stained Blood");
        add("ritual.neovitae.imperfect.ritual_warden", "Ritual of the Warden");
        add("text.component.animusnv.activation_crystal.shattered", "The crystal shatters after successfully activating the ritual!");
        add("text.component.animusnv.activation_crystal.unbound", "Crystal must be bound to activate rituals!");
        add("text.component.animusnv.blood_core.spreading_disabled", "Blood Core: Spreading disabled");
        add("text.component.animusnv.blood_core.spreading_enabled", "Blood Core: Spreading enabled");
        add("text.component.animusnv.chains.capture_failed", "This entity is too powerful to capture!");
        add("text.component.animusnv.diviner.altar_info", "§6=== Ara Vitae Info ===");
        add("text.component.animusnv.diviner.arcane_rune_dislocation", "  + Dislocation Bonus Active");
        add("text.component.animusnv.diviner.arcane_rune_header", "=== Arcane Rune Status ===");
        add("text.component.animusnv.diviner.arcane_rune_powered", "Powered: ");
        add("text.component.animusnv.diviner.arcane_rune_powered_no", "No");
        add("text.component.animusnv.diviner.arcane_rune_powered_yes", "Yes");
        add("text.component.animusnv.diviner.arcane_rune_source", "Source: %d / %d");
        add("text.component.animusnv.diviner.arcane_rune_speed", "Speed Multiplier: %s");
        add("text.component.animusnv.diviner.essence_info", "§cEssentia Vitae: §f%d / %d");
        add("text.component.animusnv.diviner.max_tier", "Altar is already at maximum tier!");
        add("text.component.animusnv.diviner.missing", "Missing component:");
        add("text.component.animusnv.diviner.missing_blocks", "Missing %s block%s in inventory");
        add("text.component.animusnv.diviner.multiplier_capacity", "Capacity: ");
        add("text.component.animusnv.diviner.multiplier_dislocation", "Dislocation: ");
        add("text.component.animusnv.diviner.multiplier_efficiency", "Efficiency: ");
        add("text.component.animusnv.diviner.multiplier_orb", "Orb Capacity: ");
        add("text.component.animusnv.diviner.multiplier_sacrifice", "Sacrifice: ");
        add("text.component.animusnv.diviner.multiplier_self_sacrifice", "Self-Sacrifice: ");
        add("text.component.animusnv.diviner.multiplier_speed", "Speed: ");
        add("text.component.animusnv.diviner.multiplier_tick_rate", "Tick Rate: ");
        add("text.component.animusnv.diviner.multipliers_header", "=== Altar Bonuses ===");
        add("text.component.animusnv.diviner.no_blocks_found", "No required blocks found in inventory!");
        add("text.component.animusnv.diviner.no_blocks_to_place", "No blocks needed or missing materials in inventory");
        add("text.component.animusnv.diviner.no_ritual_set", "No ritual set");
        add("text.component.animusnv.diviner.no_ritual_to_dismantle", "No ritual to dismantle");
        add("text.component.animusnv.diviner.no_upgrade_needed", "No upgrade blocks needed!");
        add("text.component.animusnv.diviner.obstructed", "Altar component obstructed");
        add("text.component.animusnv.diviner.owner_label", "Owner: ");
        add("text.component.animusnv.diviner.placed_blocks", "Placed %s block%s for Tier %s");
        add("text.component.animusnv.diviner.ritual_dismantled", "Ritual dismantled!");
        add("text.component.animusnv.diviner.ritual_label", "Ritual: ");
        add("text.component.animusnv.diviner.rune_breakdown_header", "=== Runes ===");
        add("text.component.animusnv.diviner.showing_upgrade", "Showing upgrade requirements for Tier %s");
        add("text.component.animusnv.diviner.sneak_to_autoplace", "Sneak + Right-click to auto-place");
        add("text.component.animusnv.diviner.sneak_to_build", "Sneak + Right-click to build Tier %s");
        add("text.component.animusnv.diviner.sneak_to_dismantle", "Sneak + Right-click to dismantle");
        add("text.component.animusnv.diviner.status_active", "Active");
        add("text.component.animusnv.diviner.status_inactive", "Inactive");
        add("text.component.animusnv.diviner.status_label", "Status: ");
        add("text.component.animusnv.diviner.tier_info", "§cTier: §f%d");
        add("text.component.animusnv.equivalency.added", "Added %s to selection (%s/%s)");
        add("text.component.animusnv.equivalency.already_selected", "This block is already selected");
        add("text.component.animusnv.equivalency.cleared", "Cleared selected blocks");
        add("text.component.animusnv.equivalency.max_selected", "Maximum %s blocks can be selected");
        add("text.component.animusnv.equivalency.no_blocks", "You do not have this block in your inventory");
        add("text.component.animusnv.equivalency.no_ev", "Not enough EV. Need %s EV");
        add("text.component.animusnv.equivalency.no_matches", "No matching blocks found in radius");
        add("text.component.animusnv.equivalency.no_selection", "No blocks selected. Sneak + right-click a block to select it");
        add("text.component.animusnv.equivalency.radius", "Radius: %s");
        add("text.component.animusnv.equivalency.radius_changed", "Radius: %s (%s×%s area)");
        add("text.component.animusnv.equivalency.same_block_warning", "All matching blocks would be replaced with the same type!");
        add("text.component.animusnv.equivalency.started", "Replacing %s blocks...");
        add("text.component.animusnv.free_soul.activated", "Free Soul activated - ghost mode for %s seconds");
        add("text.component.animusnv.free_soul.already_spectator", "Already in ghost mode!");
        add("text.component.animusnv.free_soul.expired", "Ghost mode expired - returned to previous game mode (+10 health)");
        add("text.component.animusnv.free_soul.no_ev", "Not enough EV to activate Free Soul");
        add("text.component.animusnv.free_soul.on_cooldown", "Free Soul on cooldown: %s seconds remaining");
        add("text.component.animusnv.free_soul.returning", "Returning to original position...");
        add("text.component.animusnv.free_soul.saved", "The Free Soul saves you from death!");
        add("text.component.animusnv.hand_of_death.execute", "⚰ EXECUTED: %s");
        add("text.component.animusnv.healing.cannot_drop", "Fragment of Healing cannot be dropped!");
        add("text.component.animusnv.healing.warning", "Warning: This item cannot be moved or dropped once obtained!");
        add("text.component.animusnv.hellforged_bow.bound", "Hellforged Bow bound to you");
        add("text.component.animusnv.hellforged_bow.execute", "§4⚰ EXECUTED: %s");
        add("text.component.animusnv.hellforged_bow.no_ev", "Not enough EV to fire!");
        add("text.component.animusnv.hellforged_bow.not_bound", "Hellforged Bow is not bound!");
        add("text.component.animusnv.key.cannot_bind_key", "A Key of Binding cannot bind another Key of Binding!");
        add("text.component.animusnv.key.item_bound", "Item bound to %s via Key of Binding");
        add("text.component.animusnv.monk.no_ev", "Not enough EV - Sigil of the Demon Monk deactivated");
        add("text.component.animusnv.remedium.activated", "Remedium Sigil activated - cleansing negative effects");
        add("text.component.animusnv.remedium.deactivated", "Remedium Sigil deactivated");
        add("text.component.animusnv.remedium.no_ev", "Not enough EV - Remedium Sigil deactivated");
        add("text.component.animusnv.reparare.activated", "Reparare Sigil activated - repairing items");
        add("text.component.animusnv.reparare.deactivated", "Reparare Sigil deactivated");
        add("text.component.animusnv.reparare.no_ev", "Not enough EV - Reparare Sigil deactivated");
        add("text.component.animusnv.sacrifice.too_powerful", "This enemy is too powerful to be sacrificed!");
        add("text.component.animusnv.sentient_bow.no_spiritus", "Not enough Spiritus to fire!");
        add("text.component.animusnv.spear.activated", "Bound Spear activated - 50EV per attack");
        add("text.component.animusnv.spear.bound_success", "Bound Spear bound to you");
        add("text.component.animusnv.spear.deactivated", "Bound Spear deactivated");
        add("text.component.animusnv.spear.no_ev_attack", "Not enough EV to attack!");
        add("text.component.animusnv.spear.no_ev_throw", "Not enough EV to throw!");
        add("text.component.animusnv.temporal.activated", "Temporal acceleration set to %sx speed for %s seconds");
        add("text.component.animusnv.temporal.disallowed", "This block cannot be accelerated");
        add("text.component.animusnv.temporal.gag_active", "This block is already being accelerated");
        add("text.component.animusnv.rectifier.linked", "Linked to Ara Vitae at: %s, %s, %s");
        add("text.component.animusnv.rectifier.no_altar", "No Ara Vitae found nearby");
        add("text.component.animusnv.rectifier.orb_placed", "Orb of Vitae placed");
        add("text.component.animusnv.rectifier.orb_removed", "Orb of Vitae removed");
        add("text.component.animusnv.rectifier.orb_not_bound", "Orb of Vitae must be bound first");

        add("text.component.animusnv.temporal.no_ev", "Not enough EV! Requires %s EV");
        add("text.component.animusnv.temporal.no_tile", "No block entity at target location");
        add("text.component.animusnv.ticket.antilife", "AntiLife");
        add("text.component.animusnv.ticket.apple", "Blood Apple");
        add("text.component.animusnv.ticket.boundless_nature", "Boundless Nature");
        add("text.component.animusnv.ticket.builder", "Builder");
        add("text.component.animusnv.ticket.chains", "Chains");
        add("text.component.animusnv.ticket.consumption", "Consumption");
        add("text.component.animusnv.ticket.culling", "Culling");
        add("text.component.animusnv.ticket.eldritch", "Eldritch Will");
        add("text.component.animusnv.ticket.entropy", "Entropy");
        add("text.component.animusnv.ticket.equivalency", "Sigil of Equivalency");
        add("text.component.animusnv.ticket.floral_supremacy", "Floral Supremacy");
        add("text.component.animusnv.ticket.free_soul", "Free Soul");
        add("text.component.animusnv.ticket.heavenly_wrath", "Heavenly Wrath");
        add("text.component.animusnv.ticket.leach", "Leach");
        add("text.component.animusnv.ticket.luna", "Luna");
        add("text.component.animusnv.ticket.monk", "Sigil of the Demon Monk");
        add("text.component.animusnv.ticket.monk_execute", "Monk Execute");
        add("text.component.animusnv.ticket.nolite_ignem", "Nolite Ignem");
        add("text.component.animusnv.ticket.animal_luring", "Animal Luring");
        add("text.component.animusnv.ticket.persistence", "Persistence");
        add("text.component.animusnv.ticket.relentless_tides", "Relentless Tides");
        add("text.component.animusnv.ticket.remedium", "Remedium");
        add("text.component.animusnv.ticket.reparare", "Reparare");
        add("text.component.animusnv.ticket.serenity", "Serenity");
        add("text.component.animusnv.ticket.siphon", "Siphon");
        add("text.component.animusnv.ticket.sol", "Sol Ritual");
        add("text.component.animusnv.ticket.source_vitaeum", "Source Vitaeum");
        add("text.component.animusnv.ticket.steadfast", "Steadfast Heart");
        add("text.component.animusnv.ticket.storm", "Storm");
        add("text.component.animusnv.ticket.temporal_dominance", "Temporal Dominance");
        add("text.component.animusnv.ticket.transposition", "Transposition");
        add("text.component.animusnv.ticket.unmaking", "Unmaking");
        add("text.component.animusnv.transposition.cleared", "Transposition cleared");
        add("text.component.animusnv.transposition.no_teleposer", "No Teleposer bound! Sneak + Right-click a Teleposer to bind it.");
        add("text.component.animusnv.transposition.not_enough_ev", "Not enough EV to teleport! Need %s EV");
        add("text.component.animusnv.transposition.player_must_sneak", "Cannot teleport players unless they are sneaking!");
        add("text.component.animusnv.transposition.set", "Position set");
        add("text.component.animusnv.transposition.teleported", "Teleported %s to Teleposer!");
        add("text.component.animusnv.transposition.teleposer_bound", "Teleposer bound! Attack entities to teleport them here.");
        add("text.component.animusnv.transposition.teleposer_missing", "Bound Teleposer no longer exists!");
        add("text.component.animusnv.transposition.unmovable", "Block cannot be moved");
        add("text.component.holdingitem", "You must be holding an item!");
        add("tooltip.animusnv.activation_crystal.flavour", "A fragile crystal of power");
        add("tooltip.animusnv.activation_crystal.info", "Used to activate NeoVitae rituals");
        add("tooltip.animusnv.activation_crystal.warning", "Shatters after one use!");
        add("tooltip.animusnv.arcane_rune.flavour", "An altar rune powered by Ars Nouveau Source");
        add("tooltip.animusnv.arcane_rune.info", "Drains 1000 Source from nearby jars every 10 seconds");
        add("tooltip.animusnv.arcane_rune.powered", "Powered: Speed +15%, Dislocation bonus");
        add("tooltip.animusnv.arcane_rune.unpowered", "Unpowered: Speed -50%");
        add("tooltip.animusnv.blood_apple.flavour", "An apple infused with Vitaemancy");
        add("tooltip.animusnv.blood_apple.info", "Restores 4 hunger and 9.6 saturation");
        add("tooltip.animusnv.blood_apple.ev", "Grants 200 EV when consumed");
        add("tooltip.animusnv.blood_core.flavour", "The heart of Vitaemancy");
        add("tooltip.animusnv.blood_core.info", "Used in NeoVitae altar construction");
        add("tooltip.animusnv.blood_core.multiblock", "Place as part of altar structure");
        add("tooltip.animusnv.blood_enhanced", "Blood Enhanced");
        add("tooltip.animusnv.blood_orb_transcendent.flavour", "Beyond mortal comprehension");
        add("tooltip.animusnv.blood_orb_transcendent.info", "Holds %s EV");
        add("tooltip.animusnv.blood_sapling.flavour", "A sapling born from blood");
        add("tooltip.animusnv.blood_sapling.info", "Grows into a Blood Wood tree");
        add("tooltip.animusnv.bound_to", "Bound to: ");
        add("tooltip.animusnv.conversion_rate", "Conversion: %s EV → %s mana per second");
        add("tooltip.animusnv.crystallized_spiritus.altar", "Acts as a valid CRYSTAL component");
        add("tooltip.animusnv.crystallized_spiritus.flavour", "Spiritus crystallized into solid form");
        add("tooltip.animusnv.crystallized_spiritus.info", "Required component for Tier 6 Ara Vitaes");
        add("tooltip.animusnv.currentOwner", "Owner: %s");

        add("tooltip.animusnv.sanguine_rectifier.desc", "Converts Essentia Vitae to EvilCraft Blood and vice versa");
        add("tooltip.animusnv.sanguine_rectifier.ev_to_blood", "EV \u2192 Blood: Drains from bound Orb, fills adjacent tanks");
        add("tooltip.animusnv.sanguine_rectifier.blood_to_altar", "Blood \u2192 Altar: Pipe blood in, transfers to linked Ara Vitae");
        add("tooltip.animusnv.sanguine_rectifier.rate", "Transfer rate scales with altar speed runes");
        add("tooltip.animusnv.sanguine_rectifier.ev_disabled", "EV to Blood conversion is disabled by server config");

        add("jei.animusnv.sanguine_rectifier.info", "The Sanguine Rectifier bridges NeoVitae and EvilCraft. Place near an Ara Vitae and insert a bound Orb of Vitae. It converts EV from the bound network into EvilCraft blood, filling adjacent fluid tanks. It can also accept piped EvilCraft blood and transfer it into the linked altar. Transfer rates scale with the altar's speed runes.");

        add("guide.animusnv.entry.sanguine_rectifier", "Sanguine Rectifier");
        add("tooltip.animusnv.diabolical_fungi.conversion", "1 Spiritus = 50 mana (configurable), bonus for variety");
        add("tooltip.animusnv.diabolical_fungi.flavour", "Devil's Tooth Mushroom - Feeds on Spiritus");
        add("tooltip.animusnv.diabolical_fungi.info", "Consumes Spiritus from the chunk to generate mana");
        add("tooltip.animusnv.diviner.altar_autoplace", "Sneak + Right-click altar to auto-place upgrade");
        add("tooltip.animusnv.diviner.altar_ghost", "Right-click altar to show upgrade ghost blocks");
        add("tooltip.animusnv.diviner.auto_build", "Sneak + Right-click altar to auto-place upgrade blocks");
        add("tooltip.animusnv.diviner.first", "Right-click altar to divine structure");
        add("tooltip.animusnv.diviner.ghost_blocks", "Hold while looking at altar to show tier upgrade preview");
        add("tooltip.animusnv.diviner.ritual_dismantle", "Sneak + Right-click ritual to dismantle");
        add("tooltip.animusnv.diviner.ritual_info", "Right-click ritual to show info");
        add("tooltip.animusnv.diviner.second", "Sneak right-click to place phantom blocks");
        add("tooltip.animusnv.diviner.third", "Right-click with components to build");
        add("tooltip.animusnv.equivalency.hold_sneak", "  [Hold Sneak for details]");
        add("tooltip.animusnv.equivalency.radius_info", "Radius: %s (%sx%s area)");
        add("tooltip.animusnv.equivalency.scroll_adjust", "Sneak + Scroll to adjust (1-%s)");
        add("tooltip.animusnv.hand_of_death.execute", "Execute: Instantly kill targets below 15% health");
        add("tooltip.animusnv.hand_of_death.lifesteal", "Lifesteal: Heal 20% of damage dealt");
        add("tooltip.animusnv.hand_of_death.ultimate", "Soul Reaper of Vitaemancy");
        add("tooltip.animusnv.healing.flavour", "Passively heals the user");
        add("tooltip.animusnv.healing.info", "Heals 1 health every 10 seconds");
        add("tooltip.animusnv.healing.permanent", "WARNING: Cannot be moved or dropped!");
        add("tooltip.animusnv.healing.rate", "Each additional fragment reduces time by 0.25s");
        add("tooltip.animusnv.hellforged_bow.charge", "Charge bonus: up to %sx damage at full charge");
        add("tooltip.animusnv.hellforged_bow.execute", "Execute: Instant kill below %s%% health");
        add("tooltip.animusnv.hellforged_bow.flavour", "Forged in the depths of the demon realm");
        add("tooltip.animusnv.hellforged_bow.info", "Draws power from your Essentia Vitae network");
        add("tooltip.animusnv.hellforged_bow.ev_cost", "Base EV cost: %s per shot");
        add("tooltip.animusnv.hellforged_bow.piercing", "Arrows pierce through enemies");
        add("tooltip.animusnv.hellforged_bow.spiritus_type", "Attuned Spiritus: %s");
        add("tooltip.animusnv.imperfect_ritual_stone.info", "Place a block on top and right-click to activate a ritual");
        add("tooltip.animusnv.key", "Key Binding");
        add("tooltip.animusnv.key.curio", "Equip in curio slot or hold in offhand to bind items");
        add("tooltip.animusnv.key.hold_offhand", "Hold in offhand to bind items to %s");
        add("tooltip.animusnv.key.unbound", "Unbound - Right-click to bind");
        add("tooltip.animusnv.mana_stored", "Mana: %s / %s");
        add("tooltip.animusnv.mob_soul.info", "Right-click on a block to release");
        add("tooltip.animusnv.mob_soul.type", "Entity");
        add("tooltip.animusnv.not_bound", "Not bound");
        add("tooltip.animusnv.requires_botania", "Requires Botania");
        add("tooltip.animusnv.rune_unleashed_nature.acceleration", "When charged: Acceleration bonus (faster altar processing)");
        add("tooltip.animusnv.rune_unleashed_nature.capacity", "Always active: Capacity bonus (increases EV storage)");
        add("tooltip.animusnv.rune_unleashed_nature.flavour", "A hybrid NeoVitae altar rune powered by Botania mana");
        add("tooltip.animusnv.rune_unleashed_nature.info", "Drains 10 mana/second from internal buffer");
        add("tooltip.animusnv.rune_unleashed_nature.orb", "Always active: Half Rune of the Orb bonus (Anima Storage)");
        add("tooltip.animusnv.runic_sentient_scythe.attack_speed", "30% faster attack speed");
        add("tooltip.animusnv.runic_sentient_scythe.enhanced", "Enhanced Sentient Scythe with runic modifications");
        add("tooltip.animusnv.runic_sentient_scythe.malum", "Harvests souls for Malum's spirit system");
        add("tooltip.animusnv.sentient_bow.damage_bonus", "+%s Arrow Damage");
        add("tooltip.animusnv.sentient_bow.flavour", "A bow infused with demonic essence");
        add("tooltip.animusnv.sentient_bow.info", "Arrows gain power from Spiritus");
        add("tooltip.animusnv.sentient_bow.spiritus_drops", "Drops Spiritus matching your attuned type on kill");
        add("tooltip.animusnv.sentient_shield.flavour", "A shield powered by the will of demons");
        add("tooltip.animusnv.sentient_shield.spiritus_bonus", "+30% Spiritus gained while equipped");
        add("tooltip.neovitae.sentientShield.rider.raw", "Block grants Strength II for 5 seconds");
        add("tooltip.neovitae.sentientShield.rider.nihilum", "No special block effect");
        add("tooltip.neovitae.sentientShield.rider.vindicta", "Block reflects 30% damage and applies Weakness for 5 seconds");
        add("tooltip.neovitae.sentientBow.rider.raw", "Standard damage scaling per shot");
        add("tooltip.neovitae.sentientBow.rider.nihilum", "Heaviest damage scaling per shot");
        add("tooltip.neovitae.sentientBow.rider.vindicta", "Lighter damage per shot");
        add("tooltip.neovitae.sentientSpear.rider.raw", "Standard damage scaling");
        add("tooltip.neovitae.sentientSpear.rider.nihilum", "Heavy damage; slower attack speed");
        add("tooltip.neovitae.sentientSpear.rider.vindicta", "Lighter damage; faster swings and bonus movement speed");
        add("tooltip.animusnv.sigil.active", "Status: Active");
        add("tooltip.animusnv.sigil.boundless_nature.flavour", "Channels Essentia Vitae into mana");
        add("tooltip.animusnv.sigil.boundless_nature.info", "EV-powered mana tablet for Botania tools, tiny buffer");
        add("tooltip.animusnv.sigil.boundless_nature.toggle", "Shift-right-click to toggle active/inactive");
        add("tooltip.animusnv.sigil.builder.flavour", "Im fast as **** Boys");
        add("tooltip.animusnv.sigil.builder.info", "Accelerates block placement speed");
        add("tooltip.animusnv.sigil.chains.flavour", "Binds the soul of an enemy");
        add("tooltip.animusnv.sigil.chains.info", "Right-click entity to capture into Mob Soul");
        add("tooltip.animusnv.sigil.consumption.flavour", "All Consuming...");
        add("tooltip.animusnv.sigil.consumption.info", "Converts everything it touches to antilife");
        add("tooltip.animusnv.sigil.equivalency.1", "Sneak + right-click blocks to select up to 20 types");
        add("tooltip.animusnv.sigil.equivalency.2", "Right-click to replace all matching blocks in radius");
        add("tooltip.animusnv.sigil.equivalency.selected", "Selected: %s/%s blocks");
        add("tooltip.animusnv.sigil.free_soul.cooldown", "Death prevention cooldown: %s seconds");
        add("tooltip.animusnv.sigil.free_soul.cooldown_remaining", "Cooldown: %s seconds remaining");
        add("tooltip.animusnv.sigil.free_soul.cost", "Costs %sEV per use");
        add("tooltip.animusnv.sigil.free_soul.death", "Prevents death like a Totem of Undying, heals +10 health");
        add("tooltip.animusnv.sigil.free_soul.duration", "Lasts %s seconds, returns you to start position");
        add("tooltip.animusnv.sigil.free_soul.flavour", "Liberates the soul from the body");
        add("tooltip.animusnv.sigil.free_soul.info", "Right-click to enter ghost mode for scouting");
        add("tooltip.animusnv.sigil.heavenly_wrath.flavour", "Smites enemies from above");
        add("tooltip.animusnv.sigil.heavenly_wrath.info", "Levitates enemies then drops them for fall damage");
        add("tooltip.animusnv.sigil.inactive", "Status: Inactive");
        add("tooltip.animusnv.sigil.leach.flavour", "Drains life from nature");
        add("tooltip.animusnv.sigil.leach.info", "Activate to replenish hunger using nearby plants or inventory crops");
        add("tooltip.animusnv.sigil.monk.active", "Status: Active");
        add("tooltip.animusnv.sigil.monk.cost", "Costs 5 EV per hit or block mined");
        add("tooltip.animusnv.sigil.monk.damage", "+%s Unarmed Damage with knockback");
        add("tooltip.animusnv.sigil.monk.execute", "Execute: Instant kill below threshold, +200 EV, -5 Spiritus");
        add("tooltip.animusnv.sigil.monk.flavour", "The path of inner strength");
        add("tooltip.animusnv.sigil.monk.inactive", "Status: Inactive");
        add("tooltip.animusnv.sigil.monk.info", "Equip as curio. Enhances unarmed combat, mining, and defense.");
        add("tooltip.animusnv.sigil.monk.kill_bonus", "On kill: Resistance II (5s) + Regeneration (2s)");
        add("tooltip.animusnv.sigil.monk.mining", "Mine with the power of your fist");
        add("tooltip.animusnv.sigil.monk.soul_snare", "Applies Spiritus Snare II (2s) - guaranteed Spiritus drops");
        add("tooltip.animusnv.sigil.monk.spiritus_bonus", "Spiritus: +1-15%% max HP damage (scales 1-4096 Spiritus)");
        add("tooltip.animusnv.sigil.remedium.active", "Status: Active");
        add("tooltip.animusnv.sigil.remedium.cost", "Removes negative effects once per second at the cost of EV");
        add("tooltip.animusnv.sigil.remedium.flavour", "Cleanses harmful effects");
        add("tooltip.animusnv.sigil.remedium.inactive", "Status: Inactive");
        add("tooltip.animusnv.sigil.remedium.info", "Right-click to toggle active/inactive");
        add("tooltip.animusnv.sigil.reparare.active", "Status: Active");
        add("tooltip.animusnv.sigil.reparare.cost", "Repairs items periodically (%sEV per damage)");
        add("tooltip.animusnv.sigil.reparare.flavour", "Repairs damaged items");
        add("tooltip.animusnv.sigil.reparare.inactive", "Status: Inactive");
        add("tooltip.animusnv.sigil.reparare.info", "Right-click to toggle active/inactive");
        add("tooltip.animusnv.sigil.storm.flavour", "Calls down lightning and disturbs fish");
        add("tooltip.animusnv.sigil.storm.info", "Right-click to summon lightning bolt");
        add("tooltip.animusnv.sigil.temporal_dominance.1", "Sneak + right-click on a block entity to accelerate it");
        add("tooltip.animusnv.sigil.temporal_dominance.2", "First use: 2x speed for 30s (1000 EV)");
        add("tooltip.animusnv.sigil.temporal_dominance.3", "Each use doubles speed and cost, max 32x");
        add("tooltip.animusnv.sigil.temporal_dominance.4", "At max level, costs 1000 EV to refresh timer");
        add("tooltip.animusnv.sigil.transposition.flavour", "Moves blocks");
        add("tooltip.animusnv.sigil.transposition.info", "Right-click to store/place blocks");
        add("tooltip.animusnv.sigil.transposition.stored", "Stored: %s");
        add("tooltip.animusnv.spear_bound.behaves_diamond", "Behaves like Diamond Spear");
        add("tooltip.animusnv.spear_bound.bind", "Sneak + Right-Click to bind");
        add("tooltip.animusnv.spear_bound.bound_to", "Bound to: %s");
        add("tooltip.animusnv.spear_bound.cost", "Costs 50EV per attack/throw");
        add("tooltip.animusnv.spear_bound.first", "A Roman javelin bound to your soul");
        add("tooltip.animusnv.spear_bound.second", "Strikes enemies in an area");
        add("tooltip.animusnv.spear_bound.status_activated", "Status: Activated");
        add("tooltip.animusnv.spear_bound.status_deactivated", "Status: Deactivated");
        add("tooltip.animusnv.spear_bound.toggle", "Sneak + Right-Click to toggle");
        add("tooltip.animusnv.spear_bound.unbound", "Unbound");
        add("tooltip.animusnv.spear_diamond.flavour", "A superior Roman javelin");
        add("tooltip.animusnv.spear_diamond.info", "Thrown weapon with increased damage");
        add("tooltip.animusnv.spear_iron.flavour", "A Roman javelin");
        add("tooltip.animusnv.spear_iron.info", "Thrown weapon that deals damage");
        add("tooltip.animusnv.spear_sentient.aoe", "Applies effects in an area when thrown");
        add("tooltip.animusnv.spear_sentient.damage_bonus", "+%s Attack Damage");
        add("tooltip.animusnv.spear_sentient.flavour", "A javelin empowered by Spiritus");
        add("tooltip.animusnv.spear_sentient.info", "Scales with Spiritus like the Sentient Sword");
        add("tooltip.animusnv.spear_sentient.level", "Level: %s (%s Spiritus)");
        add("tooltip.animusnv.transposition.teleposer_location", "Teleposer: %s, %s, %s");
        add("tooltip.animusnv.unbound_bind", "Unbound - Right-click to bind");
        add("tooltip.neovitae.sigil.builder.desc", "Accelerates block placement speed");
        add("tooltip.neovitae.sigil.chains.desc", "Binds the soul of an enemy - right-click to capture into a Mob Soul");
        add("tooltip.neovitae.sigil.consumption.desc", "Converts everything it touches to antilife");
        add("tooltip.neovitae.sigil.crimson_will.desc", "Channels crimson will to empower spellcasting");
        add("tooltip.neovitae.sigil.equivalency.desc", "Sneak + right-click to select blocks, right-click to replace all matching blocks in radius");
        add("tooltip.neovitae.sigil.free_soul.desc", "Liberates the soul from the body for scouting");
        add("tooltip.neovitae.sigil.heavenly_wrath.desc", "Levitates enemies then drops them for fall damage");
        add("tooltip.neovitae.sigil.leach.desc", "Replenishes hunger using nearby plants or inventory crops");
        add("tooltip.neovitae.sigil.monk.desc", "Enhances unarmed combat, mining, and defense");
        add("tooltip.neovitae.sigil.remedium.desc", "Cleanses harmful effects");
        add("tooltip.neovitae.sigil.reparare.desc", "Periodically repairs damaged items");
        add("tooltip.neovitae.sigil.storm.desc", "Calls down lightning and disturbs fish");
        add("tooltip.neovitae.sigil.temporal_dominance.desc", "Accelerates block entities, doubling speed with each use");
        add("tooltip.neovitae.sigil.transposition.desc", "Right-click to store and place blocks");

        this.langCache.data().forEach(this::add);
    }
}
